### ISSUE TITLE
FIRST ISSUE TO SOLVE: Fix the tests

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rust#10]
The tests should work with the latest version of MeiliSearch (currently the v0.12.0)

```bash
docker run -it --rm -p 7700:7700 getmeili/meilisearch:v0.12.0 ./meilisearch  --no-analytics=true
```

Current failure:
```bash
failures:

---- src/client.rs - client::Client::get_stats (line 162) stdout ----
Test executable failed (exit code 101).

stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown("invalid type: null, expected a string at line 1 column 39")', src/client.rs:8:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Edit

<s>this failure appears only if the MeiliSearch instance already contains indexes. It should not fail in this context. We should fix this issue.</s> => not true, see this [job failure](https://github.com/meilisearch/meilisearch-rust/pull/19/checks?check_run_id=895051108). The bug seems to be random.

**Comment by Mubelotix** [comment]
One of the two Stats struct need one field to take an Option<String> instead of a String because it seems nullable and I did not see it before.
