### ISSUE TITLE
Error with ProcessedStatus

### ISSUE THREAD

**Issue by sanders41** [meilisearch/meilisearch-rust#107]
I was looking at the possibility of adding the get all update status route in #39 and have run into an issue. According to the [documentation](https://docs.meilisearch.com/reference/api/updates.html#get-all-update-status) the response will look like:

```json
[
  {
    "status": "processed",
    "updateId": 1,
    "type": {
      "name": "DocumentsAddition",
      "number": 4
    },
    "duration": 0.076980613,
    "enqueuedAt": "2019-12-07T21:16:09.623944Z",
    "processedAt": "2019-12-07T21:16:09.703509Z"
  }
]

```

but when I test I get an error ```ParseError(Error("missing field `duration`", line: 1, column: 325)```. This error seems to resolve and the response does include the duration and processedAt information if I do `sleep(Duration::from_secs(1));` after adding documents.

I checked what response I get in the [python clients test](https://github.com/meilisearch/meilisearch-python/blob/628552573181c4d348489362e694d3d2a32372ab/meilisearch/tests/index/test_index_update_meilisearch.py#L11) and the result in the test is:

```py
[
    {
        'status': 'enqueued', 
        'updateId': 0,
        'type': {
            'name': 'DocumentsAddition',
            'number': 30
        },
        'enqueuedAt': '2021-02-14T14:07:09.364505700Z'
    },
    {
        'status': 'enqueued',
        'updateId': 1,
        'type': {
             'name': 'DocumentsAddition',
             'number': 30
        },
        'enqueuedAt': '2021-02-14T14:07:09.373833600Z'
    }
]
```

Since Python is putting the information into a dictionary the tests passes, but if the end user is expecting the keys to be there and used, for example, `result["duration"]` instead of `result.get("duration")` this would error.

My guess is that in the documentation it is assuming that the documents will always be processed before checking the status, but this doesn't seem to be the case? If that is correct would updating [ProcessedStatus](https://github.com/meilisearch/meilisearch-rust/blob/ae1df1208bc8a6647905b9758705687ea4ca4839/src/progress.rs#L111) to the following be appropriate?

```rs
#[derive(Deserialize, Debug)]
#[serde(rename_all = "camelCase")]
pub struct ProcessedStatus {
    pub update_id: u64,
    #[serde(rename = "type")]
    pub update_type: UpdateType,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub duration: Option<f64>,        // in seconds
    pub enqueued_at: String,  // TODO deserialize to datatime
    #[serde(skip_serializing_if = "Option::is_none")]
    pub processed_at: Option<String>, // TODO deserialize to datatime
}
```

Also, if this is the case should the documentation be updated to note that these fields are optional in the response since it would affect all clients even if they don't error?

**Comment by curquiza** [comment]
Hello @sanders41! Thanks for your detailed feedback! This is appreciable

> Since Python is putting the information into a dictionary the tests passes, but if the end user is expecting the keys to be there and used, for example, result["duration"] instead of result.get("duration") this would error.

The python client is indeed one of the first clients created, so the test definitely misses some updates, like this one! Thanks for noticing it!

> If that is correct would updating ProcessedStatus to the following be appropriate?

I think this would solve the issue 🙂

> Also, if this is the case should the documentation be updated to note that these fields are optional in the response since it would affect all clients even if they don't error?

You are right, I've opened an issue in the docs repo! 🙂
https://github.com/meilisearch/documentation/issues/765
