### ISSUE TITLE
Are lifetimes really required?

### ISSUE THREAD

**Issue by ppamorim** [meilisearch/meilisearch-rust#127]
I am facing difficulty to write a script using this library due to self-referential structs in given for the code below:

```rust
use meilisearch_sdk::{document::*, client::*, search::*};
use meilisearch_sdk::indexes::Index;
use serde::{Serialize, Deserialize};
use serde_json::{Deserializer, Value};
use futures::executor::block_on;
use std::fs::File;
use read_iter::ReadIter; // also add dependency to Cargo.toml
use nop_json::{Reader, TryFromJson, ValidateJson, DebugToJson};
use futures::lock::Mutex;
use std::sync::Arc;

#[derive(TryFromJson, ValidateJson, DebugToJson, PartialEq, Serialize, Deserialize)]
struct User {
    id: usize,
    email: String,
    role: String,
    first_name: String,
    middle_name: String,
    last_name: String,
}

// That trait is required to make a struct usable by an index
impl Document for User {
    type UIDType = usize;

    fn get_uid(&self) -> &Self::UIDType {
        &self.id
    }
}

struct MeiliSearchClient<'a>  {
    client: Client<'a>,
    index: Option<Index<'a>>,
}

impl<'a> MeiliSearchClient<'a> {

    fn new() -> Self {
        MeiliSearchClient {
            client: Client::new("http://localhost:7700", "masterKey"),
            index: None,
        }
    }

    async fn process(&mut self, payload: &Vec<User>) {
        if !self.index.is_none() {
            self.index = Some(self.client.get_or_create("users").await.unwrap());
        }
        self.index
            .as_ref()
            .unwrap()
            .add_documents(payload, Some("id"))
            .await
            .unwrap();
    }

}

fn main() {

    let file = File::open("users.json").unwrap();
    let mut iter = ReadIter::new(file);
    let mut reader = Reader::new(&mut iter);

    let mut client = Arc::new(Mutex::new(MeiliSearchClient::new()));

    let mut payload: Vec<User> = Vec::with_capacity(1000);

    reader.read_array(|reader| {

        match reader.read::<User>() {

            Ok(value) => {
                payload.push(value);
                if payload.len() == 1000 {
                    let client_clone = Arc::clone(&client);
                    let payload_ref = &payload;
                    block_on(async move {
                        let mut client_locked = client_clone.lock().await;
                        client_locked.process(payload_ref).await;
                    });
                    payload.clear();
                }
            },
            Err(e) => {
                println!("{}", e);
                // block_on(async move {
                //     let mut client = client.lock().await;
                //     client.process(payload_ref).await;
                // });
                payload.clear();
            },
        }
        Ok(())
    }).unwrap();

}
```

It will not compile. Note that the problem is around the definition of the Meilisearch manager struct:

```rust
struct MeiliSearchClient<'a>  {
    client: Client<'a>,
    index: Option<Index<'a>>, //<---- Problem here
}
```

I do understand that the requirement for the lifetimes is due to the client instance inside the `Index` struct, but in general, this seems to be a non-ideal solution for an async API.

Any idea of what can be done in this example? I can see that the `Client` reference is only needed to retrieve the `host` and `apiKey`. Would be nice to migrate this into a `Config` struct that can be shared between these routes?

Regards!
Pedro

**Comment by Mubelotix** [comment]
There are lifetimes so that you we can clone everything almost for free. We used a workarround in are wasm example, which is making the client static. But it won't work if you need dynamic index names.  

We could use owned `String`s to get rid of lifetimes since lifetimes and async do not match well. But actually references are much nicer. I will try to write a safe client wrapper using owned strings usafely converted to `'static` references. Safety will be guaranteed by the logic. The goal of this wrapper will be to help library's users but actually there are always solutions (often too complex in code involving async).

**Comment by ppamorim** [comment]
@Mubelotix I migrated the code to remove all lifetimes in the code in this branch: https://github.com/ppamorim/meilisearch-rust/tree/feature/removelifetimes

I can later on open a PR, but there are still some problems like the fact that I had to remove the parameter `attributes_to_crop` because serde was having trouble to serialize the type.

I will continue working on.

**Comment by Mubelotix** [comment]
Great work! I am waiting for your PR to be ready to be reviewed.

> I still think that the benefits to have some values cloned are better than the caveats experienced in my example above.

That's right but we could also use `Rc<String>`. I am not sure if this is worth it.

**Comment by ppamorim** [comment]
@Mubelotix Thank you very much. Could you please help me to finish this PR?
