### ISSUE TITLE
Meilisearch SDK can give strange errors when running against newer meilisearch versions

### ISSUE THREAD

**Issue by aidanhs** [meilisearch/meilisearch-rust#159]
**Description**
I am using `meilisearch-sdk = "0.9.0"` against `main` of meilisearch (63daa8b15ab21d).

When I create an index and unwrap with `client.create_index("param_types", None).await.unwrap()`, I get this error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: MeiliSearchError { message: "{\"uid\":\"param_types\",\"name\":\"param_types\",\"createdAt\":\"2021-08-10T23:00:32.580595725Z\",\"updatedAt\":\"2021-08-10T23:00:32.5805
95725Z\",\"primaryKey\":null}", error_code: Unknown("missing errorCode"), error_type: Internal, error_link: "" }', src/lib.rs:175:74
```

**Expected behavior**
If there is version incompatibility, meilisearch fails in some obvious way.

**Current behavior**
I was presented with an opaque error message that gave no indication about cause or resolution.

**Environment (please complete the following information):**
- OS: Ubuntu 18.04
- MeiliSearch version: 63daa8b15ab21d
- meilisearch-rust version: 0.9.0

**Comment by Mubelotix** [comment]
@curquiza is right but I don't think we even have tests to ensure that errors are parsed successfully. We need to add these

**Comment by curquiza** [comment]
I open another issue then :)

**Comment by curquiza** [comment]
I close this issue since another issue is opened. :)
