### ISSUE TITLE
Add tests for errors

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rust#162]
Following this issue: https://github.com/meilisearch/meilisearch-rust/issues/159

Add tests to ensure that errors are parsed successfully

**Comment by bidoubiwa** [comment]
Some tests were added but more should be added: https://github.com/meilisearch/meilisearch-rust/blob/dbd0c17301faa0683bc6e7460e5a696c76864dd9/src/errors.rs#L231

**Comment by romilpunetha** [comment]
Doesn't #356 close this? If not, what more is required?

**Comment by bidoubiwa** [comment]
Hey @romilpunetha . Thanks for the interest :) 

I just checked, there seems to be a lot of new tests. If you don't find any relevant test to add, we can close this issue :)

**Comment by romilpunetha** [comment]
I believe we can. 
The only two error attributes that do not have a test case are `InvalidTenantToken` and `Yaup` because they were particularly hard to test. However, they are not used anywhere in the codebase. For all the other attributes tests exist.

**Comment by bidoubiwa** [comment]
They are thrown by the external libraries. If you manage to test them, you can open a PR :)

**Comment by romilpunetha** [comment]
@bidoubiwa Done.
