### ISSUE TITLE
WebAssembly example having compilation problem

### ISSUE THREAD

**Issue by vsndev3** [meilisearch/meilisearch-rust#165]
Compilation issue with web_app example

**Description**
Having problem while trying to compile the web assembly example

Over commit f6477d1d6be89927866659e960e7c05198cbf4d6, following issues is seen:

```
...
   Compiling gloo-events v0.1.1
   Compiling gloo-console-timer v0.1.0
   Compiling gloo-timers v0.2.1
   Compiling gloo-file v0.1.0
   Compiling gloo v0.2.1
   Compiling web_app v0.1.0 (/home/va/meilisearch-rust/examples/web_app)
error[E0277]: `Rc<std::string::String>` cannot be shared between threads safely
  --> src/lib.rs:16:1
   |
16 | / lazy_static! {
17 | |     static ref CLIENT: Client = Client::new(
18 | |         "https://finding-demos.meilisearch.com",
19 | |         "2b902cce4f868214987a9f3c7af51a69fa660d74a785bed258178b96e3480bb3",
20 | |     );
21 | | }
   | |_^ `Rc<std::string::String>` cannot be shared between threads safely
   |
  ::: /home/va/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:19:20
   |
19 |   pub struct Lazy<T: Sync>(Cell<Option<T>>, Once);
   |                      ---- required by this bound in `lazy_static::lazy::Lazy`
   |
   = help: within `Client`, the trait `Sync` is not implemented for `Rc<std::string::String>`
   = note: required because it appears within the type `Client`
   = note: this error originates in the macro `__lazy_static_create` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `web_app`

To learn more, run the command again with --verbose.

```
$ cargo --version
cargo 1.54.0 (5ae8d74b3 2021-06-22)

$ rustc --version
rustc 1.54.0 (a178d0322 2021-07-26)

Built using this command: 
~/meilisearch-rust/examples/web_app$ cargo build

Any change I could make to compile this? or something I am missing?

Thanks.

**Comment by sanders41** [comment]
@vsndev3 I just tried and was able to build without error using these flags for my build `cargo build --example web_app --target wasm32-unknown-unknown --features=sync`. If you build with the flags set do you still get errors?

**Comment by vsndev3** [comment]
@sanders41 Thanks, the build ``` cargo build --example web_app --target wasm32-unknown-unknown --features=sync ``` works, however the issue is seen if ``` wasm-pack build examples/web_app/ --target=web --no-typescript ``` 

The wasam-pack version I am using is:
```
> wasm-pack -V
wasm-pack 0.10.0

```
I am assuming it could be due to interoperability reasons by wasm-pack

**Comment by sanders41** [comment]
I can confirm I get the same error with `wasm-pack build examples/web_app/ --target=web --no-typescript` using both wasm-pack 0.9.1 and 0.10.0. I'm not very familiar with wasm so unfortunately beyond confirming I get the same error, I'm not sure of the solution.

**Comment by vsndev3** [comment]
Closing the issue, since compilation is working with cargo and due to wasm-pack.

**Comment by Mubelotix** [comment]
HI @vsndev3, building with wasm-pack is possible. Try something like

```
wasm-pack build examples/web_app/ --target=web -- --features=sync
```

If I remember well, this is how to add optional features with wasm-pack
