### ISSUE TITLE
Implement Send/Sync for Index and Client Structs

### ISSUE THREAD

**Issue by tvolk131** [meilisearch/meilisearch-rust#166]
I'm running into some trouble using this client implementation because the Index and Client structs do not implement the Send or Sync traits. As an example, because these traits are unimplemented I am getting this error from a Rocket handler:

```
error: future cannot be sent between threads safely
   --> src/main.rs:155:1
    |
155 | #[get("/search/podcasts/rss?<query>&<tags>")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ future created by async block is not `Send`
    |
    = help: within `meilisearch_sdk::indexes::Index`, the trait `Sync` is not implemented for `Rc<std::string::String>`
```

A quick look at the source code leads me to believe that for both structs, swapping out the Rc-base properties for Arcs instead should be all that is needed.

**Comment by tvolk131** [comment]
Ahh I see now that there is a feature to swap out Rcs for Arcs. My bad!

**Comment by Mubelotix** [comment]
@curquiza We should make that a default. That's a pain point for too many people.

**Comment by curquiza** [comment]
Feel free to re-open the issue if you think this is a good implementation

**Comment by tvolk131** [comment]
Hey apologies for the late reply to this - would it make sense to instead add the `sync` feature as a default feature? Then, those seeking maximal single-threaded performance can disable the feature if needed.

**Comment by curquiza** [comment]
I check with our CTO, and we open this issue following this discussion :)
https://github.com/meilisearch/meilisearch-rust/issues/176

**Comment by tvolk131** [comment]
Awesome, thanks for addressing this! Other than this issue, it's been very easy to use.
