### ISSUE TITLE
Segmentation fault v0.10.0 - when the client is used

### ISSUE THREAD

**Issue by MartianGreed** [meilisearch/meilisearch-rust#168]
Hi, I can construct the client without any issues but whenever I use the client, either for getting an index or even printing out the client I get a segmentation fault.

I'm new to rust so maybe this is my own fault...
I've experienced similiar issues with the "reqwest" lib but I saw this wasn't
``` 
  let meili_client = Client::new(
        format!("{}/api/meilisearch", &config.hostname),
        &config.meili_master_key,
   );

    // Create index if not exists
    let videos_idx: Index = match meili_client.get_index("videos").await {
        Ok(idx) => idx,
        Err(_err) => match meili_client.create_index("videos", None).await {
            Ok(idx) => idx,
            Err(_err) => {
                error!("Failed to create meilisearch index");
                std::process::exit(1)
            }
        },
    };
```

**Screenshots or Logs**
Here is a pastebin of my [Cargo.toml](https://pastebin.com/w8rDykr8)

**Environment (please complete the following information):**
- OS: [Alpine linux] with openssl-dev build-base and git installed
- MeiliSearch version: [e.g. v.0.21.0]
- meilisearch-rust version: [e.g v0.10.0]

**Comment by curquiza** [comment]
Hello @MartianGreed 

Can you give the exact error you get please? :)

**Comment by MartianGreed** [comment]
Hi, thank's for your fast answer !

The only error I get is `Segmentation fault` with RUST_BACKTRACE=1 and RUST_LOG=debug

**Comment by sanders41** [comment]
Do you by chance have other code to go along with that is using `unsafe`?

**Comment by MartianGreed** [comment]
No, I didn't use the unsafe keyword either

**Comment by MartianGreed** [comment]
By running it locally on my machine (instead of docker) I can get rid of the segmentation fault.
Nonetheless, I get this error, which I think can be easily fixed

`ParseError(Error("unknown variant `processing`, expected one of `enqueued`, `failed`, `processed`", line: 1, column: 22))`

Here is how I build my docker containers for further investigations :

```
FROM rust:1.54-alpine as planner
RUN apk add openssl-dev build-base git
WORKDIR /usr/src/app
RUN cargo install cargo-chef cargo-watch
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM rust:1.54-alpine as cacher
RUN apk add openssl-dev build-base git
WORKDIR /usr/src/app
RUN cargo install cargo-chef
COPY --from=planner /usr/src/app/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json


FROM rust:1.54-alpine as builder
RUN apk add openssl-dev build-base git
WORKDIR /usr/src/app
COPY . .
COPY --from=cacher /usr/src/app/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
RUN cargo build --release


FROM rust:1.54-alpine as dev-runtime
RUN apk add openssl-dev build-base git
WORKDIR /usr/src/app
COPY . .
COPY --from=cacher /usr/src/app/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
CMD ["cargo", "run"]


FROM alpine:latest as production-runtime
RUN apk add openssl-dev build-base git
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app ./
RUN chmod +x ./target/release/update_meilisearch_index && mv ./target/release/update_meilisearch_index /usr/bin/update_meilisearch_index
CMD ["update_meilisearch_index"]

```

required environment variables :
```
export RUST_LOG="debug" && export RUST_BACKTRACE=1 && export MEILI_MASTER_KEY="Y0uRs3cr3Tm$st3rKeY" && export PG__USER=root && export PG__PASSWORD=root && export PG__HOST=localhost && export PG__DBNAME=dbname && export PG__POOL__MAX_SIZE=16 && export PG__PORT=5432 && export HOSTNAME="http://meilisearch.tld"
```

**Comment by sanders41** [comment]
I just tried running your code and didn't get any errors. Are you using Alpine in Docker? If so can you share your Dockerfile so I can try running it the same way?

**Comment by MartianGreed** [comment]
Yes I did, I've just thought maybe it has something to do with the SSL certs ?

**Comment by sanders41** [comment]
I don't think an SSL cert would cause a segfault but maybe? Is it possible to connect to the docker container and see if there is any more information in the logs there?

**Comment by MartianGreed** [comment]
The only log I get from the container is : 
```
/usr/src/app # update_meilisearch_index
Segmentation fault
```

**Comment by sanders41** [comment]
How big is `recipe.json`? Is it possible that the container is running out of memory?

**Comment by sanders41** [comment]
I tried using your Dockerfile and so far still haven't been able to recreate the issue on my side.

**Comment by MartianGreed** [comment]
Ok, I'll try it out again tomorrow... Thanks for your help

**Comment by MartianGreed** [comment]
Thank's again for your help, I'm closing this thread because this is not meilisearch-sdk related, but more about environment.

I can properly run it my machine, but this is still not working properly on my dockers :/
