### ISSUE TITLE
Make the `sync` feature as a default feature

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rust#176]
Follow https://github.com/meilisearch/meilisearch-rust/issues/166

Check with @Kerollmops. We think it's better to use `Arc` everywhere instead of `Rc` to make the user simpler for everyone.

Even if `Arc` are sightly less performant than `Rc`
- this package is only an HTTP client, so the most performance issues are coming from the network
- it eases the usage for everyone
- it's common to do this in Rust

**Comment by Mubelotix** [comment]
This is already implemented under the `sync` feature. [This feature replaces all the `Rc`s with `Arc`s](https://github.com/meilisearch/meilisearch-rust/blob/76bcb907c7c1f44bd0f32dcd86162c60dc624be4/src/lib.rs#L116). However, it is not enabled by default and that would indeed be better.

**Comment by curquiza** [comment]
Ok, I understand better, I updated the title of the issue

**Comment by sccalabr** [comment]
I'd like to give this a try

**Comment by curquiza** [comment]
Thank you @sccalabr

**Comment by curquiza** [comment]
Closed by #179
