### ISSUE TITLE
Error when parsing error status on index creation

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch-rust#248]
Hi, @irevoire . I run your example, but it didn't fail. Although, I've narrowed down where the error comes from in my case.

I mistakenly thought that it was coming from when setting the settings, but it's in fact coming when creating the index (`client.create_index`), specifically when parsing the response body:

```
fn parse_response<Output: DeserializeOwned>(
    status_code: u16,
    expected_status_code: u16,
    body: String,
) -> Result<Output, Error> {
    if status_code == expected_status_code {
        match from_str::<Output>(&body) {
            Ok(output) => {
                trace!("Request succeed");
                return Ok(output);
            }
            Err(e) => {
                error!("Request succeeded but failed to parse response");
                return Err(Error::ParseError(e));
            }
        };
```

I can see in the console `"Request succeeded but failed to parse response"`  right before the parse error.

I will ignore the error and add the settings anyway. If I can further reduce the scope of the error, will let you know.

_Originally posted by @moy2010 in https://github.com/meilisearch/meilisearch-rust/issues/230#issuecomment-1053481355_

**Comment by moy2010** [comment]
Yup, v0.25.2 with the Rust client 0.15 :( 

But no worries, @irevoire. This is not hindering me :). Thanks for putting some time into the investigation!

**Comment by moy2010** [comment]
An update on this:

After upgrading my Actix web server to v4.0.1 and the rest of the ecosystem (Tokio, Reqwest, etc.), the errors went away. I'm suspecting that some transitive dependency from the Meilisearch package was resolving to the older version that I was depending on, and this was causing the payload parsing issues being returned by the SDK.

**Comment by irevoire** [comment]
Oh good to hear, closing then!
Thanks for the feedback :heart:
