### ISSUE TITLE
Flacky test_list_all_indexes_raw test

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch-rust#281]
**Description**
The following is a flacky test: 

https://github.com/meilisearch/meilisearch-rust/blob/09f9eb5baac017b1b0a820c4646dd671ac883de3/src/client.rs#L936-L941

See the following github-action: https://github.com/meilisearch/meilisearch-rust/runs/6304373859?check_suite_focus=true

Not sure when it was introduced

**Expected behavior**
Always succeed

**Current behavior**
Regularely fail.

Any idea @irevoire ?

**Comment by bidoubiwa** [comment]
Fixed with #315
