### ISSUE TITLE
Add cargo fmt to the CI

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch-rust#291]
We should add `cargo fmt` to the CI once meilisearch/meilisearch-rust#289 is merged

**Comment by bidoubiwa** [comment]
As #289 has been closed, a PR to format the code is required before adding cargo fmt to the CI. 

For those who wants to contribute to the formating of this repo you can re-use the code from this PR #289. They have been mostly reviewed and only required small additional changes

**Comment by VoidCupboard** [comment]
Hi! Can you explain this issue a bit more? Maybe I will be able to take it

**Comment by bidoubiwa** [comment]
`cargo fmt` checks the style of your code. The issue must be updated as the PR that was supposed to format the code was closed. 

So the idea is 
- [ ] format the code using `cargo fmt`
- [ ] Add format test in the `tests.yml` ci

**Comment by bidoubiwa** [comment]
See [example here](https://github.com/meilisearch/milli/issues/231)

**Comment by VoidCupboard** [comment]
Thanks a bunch, @bidoubiwa!
