### ISSUE TITLE
Tutorial mentionned in README: simple web app using MeiliSearch

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rust#30]
In the README, we mention a tutorial to build a simple web app using MeiliSearch
https://github.com/meilisearch/meilisearch-rust#-running-in-the-browser-with-wasm

It would be very nice to provide this kind of tutorial 🙂

**Comment by Mubelotix** [comment]
I was thinking about building it using the server hosted by the official Meilisearch team (the crate search engine). But the server is using a very old version of Meilisearch which is not supported by this crate.

**Comment by curquiza** [comment]
Hum, if this is the only thing that is annoying, I'm adding "update the MeiliSearch server of the crates.io demo" in my TODO 😉 I'll keep you in touch. I will probably do it once the v0.13.0 is out!

**Comment by curquiza** [comment]
@Mubelotix https://crates.meilisearch.com/ now runs with MeiliSearch v0.13.0! 😁

**Comment by Mubelotix** [comment]
Thanks @curquiza ! I will code a prototype soon!

**Comment by Mubelotix** [comment]
So I am going to do this now. Can I steal the html and css from crates.meilisearch.com @curquiza ? It would be funny to make a perfect clone in Rust.

**Comment by curquiza** [comment]
Of course you can! 🙂 The design was originally taken from [lib.rs](https://lib.rs/), which is not a Meili property, so don't forget to mention it in your tutorial as Kero did for crates.meilisearch.com.
Thanks @Mubelotix! 🚀

**Comment by eskombro** [comment]
Hey @Mubelotix 

If you need a hosted MeiliSearch to build this, let me know, I'll provide you with a v0.16.0 server for it during development.
