### ISSUE TITLE
Missing field `nbHits`

### ISSUE THREAD

**Issue by lain-ke** [meilisearch/meilisearch-rust#300]
**Description**
After updating `meilisearch` to 0.28.0 I get the following error: missing field `nbHits`. (I have already updated the Rust SDK).

**Expected behavior**
As before the update, the search function should work as usual.

**Current behavior**
I get the error "missing field `nbHits`", probably because of the name change.

**Screenshots or Logs**
Not applicable

**Environment (please complete the following information):**
- OS: Debian on Raspberry Pi 4 (DietPi)
- Meilisearch version: Git main branch (0.28.0)
- meilisearch-rust version: Git main branch (0.17.0)

**Comment by bidoubiwa** [comment]
Hello @lain-ke 

Unfortunately this package is not yet compatible with v0.28.0. On the next release of the package it should be compatible :) 
Once #297 is merge it will be compatible

**Comment by cseblog** [comment]
Looking forward to this patch. I am also facing the same issue.

**Comment by BuyMyMojo** [comment]
Any eta on this patch?

**Comment by bidoubiwa** [comment]
Not yet, we are working on it

**Comment by bidoubiwa** [comment]
Fixed with the [last release](https://github.com/meilisearch/meilisearch-rust/releases/tag/v0.18.0) :) 

`nbHits` is now named `estimatedTotalHits`

Closing as it is fixed
