### ISSUE TITLE
ERROR meilisearch_sdk::request] Request succeeded but failed to parse response

### ISSUE THREAD

**Issue by biot023** [meilisearch/meilisearch-rust#307]
**Description**
SDK fails to parse Meilisearch success response

**Expected behavior**
No error

**Current behavior**
ERROR meilisearch_sdk::request] Request succeeded but failed to parse response
Error object: `ParseError(Error("missing field `uid`", line: 0, column: 0))`

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Meilisearch version: v.0.28.0
- meilisearch-rust version: 0.17.0, 'main' branch, 'bump-meilisearch-v0.28.0' branch

I'm sending a large number of documents via `add_documents_in_batches` -- the request succeeds but then the response fails to parse.
Could you please advise me what I've done wrong or maybe what version of the SDK I should use with our meilisearch version?
Thank you,
   Doug.

**Comment by matthias-wright** [comment]
Hi @biot023, this package is not yet compatible with v0.28.0 (see [here](https://github.com/meilisearch/meilisearch-rust/issues/300#issuecomment-1181671272)). Downgrading to v0.27.0 should do the trick :)

**Comment by biot023** [comment]
Ah, okay, thank you. For the record, I had issues with 0.27.1, too, but didn't try 0.27.0.
I don't recall the exact issues, sorry -- I was very tired by then! :)
In the meantime, a lot of work was done on our frontend against 0.28.0 so I've swapped out to the HTTP library for the backend project to preserve that.
Thanks again for getting back to me, it's really appreciated.

**Comment by bidoubiwa** [comment]
The last release is now compatible with v0.28.0! 
The bug should be fixed if you are using meilisearch v.0.28 and this crate v0.18.0
