### ISSUE TITLE
feat(docs): Fill in missing [lang] SDK examples

### ISSUE THREAD

**Issue by ryanrussell** [meilisearch/meilisearch-rust#314]
## Goal
Fill in missing Rust [lang] examples in the docs.

## Problem
This was inspired by finding that the `facets` example was missing a `Rust` tab.

This likely exists with other example and language combinations

## Background
Just noticed there some rust sdk snippets in the docs examples are missing:
https://docs.meilisearch.com/reference/api/search.html#facets

It would be nice to have a 'Rust' tab using the [Rust SDK](https://github.com/meilisearch/meilisearch-rust) for every example.

![image](https://user-images.githubusercontent.com/523300/185745703-741fd871-5ed5-4fa2-bfc3-9734a91a813e.png)

It looks like the examples are generated from this [yaml](https://github.com/meilisearch/documentation/blob/447ad12489a6acb93ce3118f01baa7dbb769d1e0/.code-samples.meilisearch.yaml).

I do see a reference to the rust code samples, perhaps this is a small tweak to include these? [Rust Code Examples](https://github.com/meilisearch/documentation/blob/90f88fe9d902b1bc69aa890c91286e50911afa15/.vuepress/code-samples/sdks.json#L45)

I am still tracing down the docs build workflow to understand how this could/should be added.

## Solution
It sounds like a path forward would be to create a matrix of all the examples and languages, to see which ones are missing.

Open to any other solutions or advice from people with more knowledge of the docs build process.

**Comment by bidoubiwa** [comment]
Hey @ryanrussell 

Since the repository is now compatible with v0.28.0, the code-samples are up to date on the documentation :) 

Closing as it is fixed.
