### ISSUE TITLE
Why is the api_key and host wrapped inside an Arc?

### ISSUE THREAD

**Issue by Jasperav** [meilisearch/meilisearch-rust#336]
I don't see any calls to `Arc::clone` in the code. Why aren't the two properties just `String`?

**Comment by bidoubiwa** [comment]
They indeed should be changed to regular String! This is a refactor that we started doing but has not been applied yet on the Client struct. 

If anyone wants to contribute to change their type to regular strings that would be very nice :)

**Comment by Jasperav** [comment]
@bidoubiwa Sure, see https://github.com/meilisearch/meilisearch-rust/pull/338
