### ISSUE TITLE
Dependabot does not suggest crates updates

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-rust#367]
Unless the crates we are using are never updated, which I doubt, dependabot does not create automatic PR's to suggest an update.

We should find out why and fix it

**Comment by curquiza** [comment]
I tried to look for the issue, I don't find any...

Here is the old dependabot file we used in the past in Meilisearch, if it can help. I can confirm it was working and that's why we removed it 😂 
https://github.com/meilisearch/meilisearch/pull/1652/files

**Comment by bidoubiwa** [comment]
Thanks! It may be a good start

**Comment by curquiza** [comment]
Looks like it's outdated since we receive dependabot update now
