### ISSUE TITLE
Add documentation on builder methods.

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-rust#372]
Currently some builder methods across the code base do not have any documentation. See for example: 

https://github.com/meilisearch/meilisearch-rust/blob/1e687c78d7d14e255474380db99b6b13941b8682/src/search.rs#L287-L303

It would be better if each of these methods are explained and showcase an example. As for example here

https://github.com/meilisearch/meilisearch-rust/blob/1e687c78d7d14e255474380db99b6b13941b8682/src/indexes.rs#L1239-L1279

**Comment by bidoubiwa** [comment]
Hey @IsaacCloos, that would be awesome if you do :) 🙏
We are not assigning to avoid blocking the PR in case the contributor does not make the PR after all, but it would be a  very valuable addition

**Comment by IsaacCloos** [comment]
Sorry for the delay! I was just able to sit down with this, and now have some preliminary research I'd like to clarify. 

# The targets

> Currently some builder methods across the code base do not have any documentation. See for example:

Here is the list I've assembled (having found three instances of `#[allow(missing_docs)]`:

- [ ] TaskQuery (19 methods)
- [ ] Settings (11 methods)
- [ ] SearchQuery (21 methods)

If there are others you'd like to add, please let me know!

# The template

> It would be better if each of these methods are explained and showcase an example. As for example here

````
/// { concise description }
///
/// # Example
///
/// ```rust
/// { runnable, doc-friendly example }
/// ```
````

If you'd like to standardize any other aspects into this template before I take a stab at this issue, please let me know!


Your feedback is much appreciated 😄

**Comment by bidoubiwa** [comment]
> If there are others you'd like to add, please let me know!

I don't see any other.

Your template answers all our needs :) Thanks a lot. I don't have anything to add or change.

**Comment by IsaacCloos** [comment]
I am now noticing that my PR has been linked into a process that would close this issue when merged. That was not my intention 😅

If there is something I can do to improve this work, or queue it for review so I can proceed with developing new documentation as this ticket requirers I'd be happy to do so 👍🏻 

Thanks for your feedback, it makes a huge difference 😄

**Comment by IsaacCloos** [comment]
![chrome_CKY0BbzUE9](https://user-images.githubusercontent.com/46393653/234090465-af6f21bf-5132-4c55-9b99-9c046dab0627.gif)

Lesson learned 😬 

Please reopen this issue. I will be more careful in the future.
