### ISSUE TITLE
Remove the need of writing to_string() everywhere in the tests by using `big_s`

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/meilisearch-rust#388]
Currently, throughout the tests we are adding `to_string()` everywhere. Which is tedious and reduces readability.

To clean the code, we should use the crate [`big_s`](https://docs.rs/big_s/latest/big_s/index.html)

## Todo

- Add `big_s` to the repo as a dev dependencies `cargo add big_s --dev`
- Import the library in every tests mod that needs it:
   ```rust
  mod tests {
    use big_s::S;
    //...
   ```

- Change all occurrences of for example `"something".to_string()` to `S("something")

**Comment by romilpunetha** [comment]
Why is this being used only for tests?

**Comment by bidoubiwa** [comment]
@irevoire may answer that
