### ISSUE TITLE
publish latest release version to crates.io

### ISSUE THREAD

**Issue by thed0ct0r** [meilisearch/meilisearch-rust#403]
hi, i've been enjoying exploring what meilisearch can offer. but have noticed that the latest version on your github releases page is [v0.21.0](https://github.com/meilisearch/meilisearch-rust/releases/tag/v0.21.0) which was released on 2022-11-28 and includes support for meilisearch 0.30.0.
yet the latest version i could find on crates.io and docs.rs is [v0.20.1](https://github.com/meilisearch/meilisearch-rust/releases/tag/v0.20.1) from 2022-10-10.

was this release pulled? or is this intentional? i'm currently pulling it straight for github, but would rather have all dependencies pulled from crates.io if possible.

**Comment by bidoubiwa** [comment]
Thanks a lot for pointing this out @thed0ct0r !
Indeed, i just checked and the publishing failed.

**Comment by thed0ct0r** [comment]
thanks for checking it out @bidoubiwa

**Comment by thed0ct0r** [comment]
hi @bidoubiwa - apologies for necrobumping this, but should i be seeing v0.21.0 on crates.io? or will this only be happening for later versions?
asking because i'm still seeing v0.20.1 on crates.io

**Comment by bidoubiwa** [comment]
Hey @thed0ct0r 
My bad, indeed I still need to release. I'll fix this today

**Comment by thed0ct0r** [comment]
@bidoubiwa - thanks, appreciate your efforts!

**Comment by bidoubiwa** [comment]
fixed by #411

**Comment by bidoubiwa** [comment]
It is released :)
