### ISSUE TITLE
Compatibility with version v0.30.5

### ISSUE THREAD

**Issue by Jasperav** [meilisearch/meilisearch-rust#415]
Is this library also compatible with Meilisearch v0.30.5? In the readme it says v0.30, but I was wondering if I could use it on the latest version.

**Comment by irevoire** [comment]
Hey, since there are no breaking change between the v0.30.0 and v0.30.5, _yes_ this library should be compatible the v0.30.5 👍

**Comment by Jasperav** [comment]
@irevoire Thanks for the confirmation!
