### ISSUE TITLE
Efficiency of the Index APIs

### ISSUE THREAD

**Issue by martin-g** [meilisearch/meilisearch-rust#424]
Hello,

First, I want to congratulate you for v1.0! I just noticed it in the news.

I am a newbie in Meilisearch, so I might be wrong but looking at the sample code at https://docs.meilisearch.com/learn/getting_started/quick_start.html#add-documents:

```rust
 let mut content = String::new();
  file
    .read_to_string(&mut content)
    .unwrap();
  let movies_docs: Vec<Movie> = serde_json::from_str(&content)
    .unwrap();

  // adding documents
  client
    .index("movies")
    .add_documents(&movies_docs, None)
    .await
    .unwrap();
```

I see that initially we have a JSON String (the `content`) that is parsed/deserialized to `Vec<Movie>` and then this vector is passed to the client which sends it to the server again as a text, i.e. the vector is JSON serialized.

I have the feeling this might be inefficient.
Would it be better to send the plain text and let the server validate that it is proper JSON.
I guess one has to use an plain HTTP client to deal with raw text ?! 

Thank you!

**Comment by irevoire** [comment]
Hey, I was wondering the same thing!
I made a proposition here; https://github.com/meilisearch/integration-guides/issues/238#issuecomment-1423330313

It would be nice if you could share your use case and explain your reasoning 😁

**Comment by martin-g** [comment]
Awesome!
