### ISSUE TITLE
Invalid type error in getting_started_add_documents_md

### ISSUE THREAD

**Issue by amaihoefner** [meilisearch/meilisearch-rust#434]
**Description**
Trying to run the sample code in the quickstart section ["Add documents"](https://docs.meilisearch.com/learn/getting_started/quick_start.html#add-documents) results in an `invalid type` error.

**Expected behavior**
`movies.json` is parsed and added to database.

**Current behavior**
The program panics with the following message:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: integer `2`, expected a string", line: 2, column: 8)', src/main.rs:24:65
```

**Comment by JaydenElliott** [comment]
Can replicate
