### ISSUE TITLE
Expose isahc crate's static-ssl feature

### ISSUE THREAD

**Issue by TcOhamtyw6lt** [meilisearch/meilisearch-rust#468]
**Description**
Building fails when OpenSSL libraries are not installed.

**Basic example**

```
   Compiling openssl-sys v0.9.87
error: failed to run custom build command for `openssl-sys v0.9.87`
```

As the isahc crate's other feature, static-curl is exposed and made default, this one should be too, to enable builds without needing OpenSSL libraries present.

**Comment by bidoubiwa** [comment]
Hey @TcOhamtyw6lt
Thanks for raising this issue 🙏 Looking at your PR :)
