### ISSUE TITLE
Empty query returns no results

### ISSUE THREAD

**Issue by longfellowone** [meilisearch/meilisearch-rust#47]
According to docs

"When q isn't specified, a placeholder search is performed, returning documents that best match other search parameters."

https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#query-q

Is there a way to provide an empty query? using a empty string returns 0 results

```rust
let query = Query::new("").with_filters("area = n1");
let results = tasks_index.search::<Task>(&query).await.unwrap().hits;
```

**Comment by curquiza** [comment]
Hello @longfellowone!

Currently, the MeiliSearch placeholder works only when passing a `q=null` or no `q` at all, but `q=''` returns indeed no result.

This will be changed in the next release! https://github.com/meilisearch/MeiliSearch/pull/916

**Comment by longfellowone** [comment]
Figured that was the case. Until the next version is released is there anyway to send in a null query using the current rust api as new() does not accept an Option?

**Comment by Mubelotix** [comment]
I will add this feature in #46. The query will be an `Option` too.

**Comment by curquiza** [comment]
FYI the next release of MeiliSearch (v0.15.0) will be out in two weeks and will contain this change (`q=''` will return results as placeholder search).
If there is any change, I will let you know as the public pre-release will be out on Monday!

**Comment by Mubelotix** [comment]
Yes, but it would be more idiomatic to make `query` optional.

**Comment by Mubelotix** [comment]
I don't understand. According to the meilisearch response, the query string is mandatory.
```
Invalid JSON: missing field `q` at line 1 column 2", error_code: BadRequest, error_type: InvalidRequest, error_link: "https://docs.meilisearch.com/error/bad_request
```

**Comment by curquiza** [comment]
@Mubelotix: Hum weird, what is the version of your MeiliSearch instance?

**Comment by Mubelotix** [comment]
Oups I ran a very old version.
