### ISSUE TITLE
Do not enforce lat/long to be between -90/-180 and 90/180

### ISSUE THREAD

**Issue by rbozan** [meilisearch/meilisearch-rust#471]
**Description**
Whenever you currently want to use the geolocation feature like so:
```ts
		return index.search(searchInput, {
			sort: [`_geoPoint(${center.x}, ${center.y}):asc`]
		});

```

It tells you that the latitude must be between -90 and 90. While this does make sense for the "real world", this enforcement means you can not use MeiliSearch for searching something within a virtual world like a game where the lat/long could be way bigger than this.

**Basic example**
I'd like to not have this enforcement between values which make sense in the real world, or at least have a way to disable the warning.

**Other**
I'd like to know if there's any technical reason why this enforcement is made, or is it just that humans are not to always be trusted?

**Comment by rbozan** [comment]
reported in meilisearch repo instead.

**Comment by bidoubiwa** [comment]
👌
