### ISSUE TITLE
Don't require tokio runtime

### ISSUE THREAD

**Issue by MCOfficer** [meilisearch/meilisearch-rust#48]
Currently, this project requires usage of the tokio runtime, using it with f.e. async-std is not possible. It would be nice if we could also use it with these other runtimes, without having to do this (yuck):
```rust
    tokio::runtime::Builder::new()
        .basic_scheduler()
        .enable_all()
        .build()?
        .block_on(do_something_async())?;
```

As far as i can see, the only reason is the dependency of reqwest.

Switching to a runtime-agnostic http client seems possible. I made out https://github.com/http-rs/surf as a good option, especially since it has a wasm-backend. One should probably wait for its [2.0 release](https://github.com/http-rs/surf/milestone/1) before switching.

**Comment by Mubelotix** [comment]
Do without `reqwest` would indeed be great. I never heard about `surf`. Is it as stable as `reqwest`?

**Comment by MCOfficer** [comment]
Once it reaches 2.0, I'd expect it to be quite stable.

Firstly, the http-rs is one of the bigger players in the whole networking topic, they know what they're doing. Secondly, surf is just an abstraction over two very stable http backends - `hyper` (which reqwest uses) and `isahc` (a curl wrapper). 

As it stands, #49 is using the `isahc`, but switching is as simple as adding a feature.

**Comment by MCOfficer** [comment]
I read up on it, and unless you are paranoid surf, is perfectly stable.

If you are paranoid, [surf is just as unstable as reqwest](https://medium.com/@shnatsel/smoke-testing-rust-http-clients-b8f2ee5db4e6), not matter which backend it uses. But at that point, *nothing* is stable.

**Comment by Mubelotix** [comment]
Since I have read [this article](https://medium.com/@shnatsel/smoke-testing-rust-http-clients-b8f2ee5db4e6) I am quite paranoid about the stability. But you should be right.

**Comment by curquiza** [comment]
Hello @MCOfficer! Welcome here, and thanks for your suggestion 🙂

@Kerollmops what do you think about `reqwest` vs `surf`?

(FYI @MCOfficer, @Kerollmops is the main contributor of the [MeiliSearch's core engine](https://github.com/meilisearch/MeiliSearch), so written in Rust)

**Comment by Kerollmops** [comment]
Hey @MCOfficer,

I like what you say about the reqwest dependency, I am convinced that this is a little ugly to deploy a whole tokio runtime to use it. However, I already tried surf and it was not that great, I [encountered some bugs](https://github.com/http-rs/surf/issues/72).

I would love to use surf instead of reqwest directly, if we do we will have to provide features to allow the user to choose [its HTTP backend runtime (reqwest, isahc)](https://docs.rs/surf/1.0.3/surf/#features).

**Comment by MCOfficer** [comment]
@Kerollmops Agreed regarding backends, i'll give the PR two passthrough features.

I checked for alternatives to surf, and there really aren't many. Most clients built on hyper are from the early async days and thus rely on tokio (namely, reqwest and yuzikaze). Everything else is either sync or abandoned. The only true alternatives are reqwest and isahc themselves (yay, reinventing the wheel), and awc (but i have to say, i'm not really trusting the actix-stack).

**Comment by curquiza** [comment]
Hello @Mubelotix and @MCOfficer!
Sorry not to have really followed this issue. Is there a final decision about this? What should we do with PR #49? 🙂

**Comment by MCOfficer** [comment]
The final decision is on you (as in, your team). I will for the time being move away from meilisearch, so it will be your code to maintain.

I haven't really worked #49 in the past weeks, but i still think it's a nice solution. `isahc` is stable and it automatically shares one client between threads, which reduces overhead without having to manage the client ourselves. It does use curl under the hood which isn't great, but i guess perfection is the enemy of the good.

I've been using my branch in production for https://odcrawler.xyz/, and I haven't seen any problems.

**Comment by curquiza** [comment]
Great to know that your changes work in production 😁
After reading your arguments, it could be great to apply your suggestion, from my POV. But I'm not a Rust expert.
@LegendreM, could you help me with this? 🙂
Also, @Mubelotix, we will not take any definitive decision without having your POV.

**Comment by Mubelotix** [comment]
I am waiting for #49 to be finished and then I will compare the CPU usage and binary size. I think it's great to make without `tokio` but if `reqwest` + `tokio` outperforms greatly `isahc` on one of these metrics, I think it would be nice to give the choice of the backend to the library user.

**Comment by MCOfficer** [comment]
> 
> 
> I am waiting for #49 to be finished and then I will compare the CPU usage and binary size. I think it's great to make without `tokio` but if `reqwest` + `tokio` outperforms greatly `isahc` on one of these metrics, I think it would be nice to give the choice of the backend to the library user.

The only things left are the passthrough feature (to control isahc's `static-curl` feature) and possibly one if-statement in `parse_response`, so the performance shouldn't change anymore. I will try to finish this in the next day, but if you have time, feel free to test it already.

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch-rust/pull/70
