### ISSUE TITLE
Testing against populated data

### ISSUE THREAD

**Issue by ppamorim** [meilisearch/meilisearch-rust#53]
## Summary

When running `cargo test` I noticed that I need to have a Meilisearch instance pre-configured before hand. This instance generally is empty and the tests are not running against a populated instance, no assert is done regarding the data that the SDK returns.

## Possible solution

I would suggest to add a pre-setup configuration for the command `cargo test`, this is possible with the runner `cargo-make`: https://sagiegurari.github.io/cargo-make/

**Comment by Mubelotix** [comment]
I know that tests are not very robust for now. We are speaking a bit about this in #29. There will be a PR that will greatly improve the old tests. You can see the proposed solution in the new tests of #46.

**Comment by bidoubiwa** [comment]
fixed by https://github.com/meilisearch/meilisearch-rust/issues/41
