### ISSUE TITLE
Upgrade tokio from 0.2 to 0.3

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rust#57]
Currently, our tests are failing when trying to upgrade tokio from 0.2 to 0.3. See this failing PR: https://github.com/meilisearch/meilisearch-rust/pull/55.

The goal of this issue is to upgrade tokio to keep our dependencies up to date.

**Comment by Mubelotix** [comment]
I tried to fix this but it is impossible because reqwest does not support tokio 0.3 yet.

**Comment by curquiza** [comment]
Ok good to know, I close the related PR of dependabot then!
Let's keep an eye on the issue you linked 🙂

**Comment by curquiza** [comment]
Tokio is not used by this repo anymore
