### ISSUE TITLE
Panic on large payloads

### ISSUE THREAD

**Issue by Geometrically** [meilisearch/meilisearch-rust#6]
On extremely large payloads (~512 MB) the SDK panics when trying to write to the index:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown("{\"message\":\"Payload to large\",\"errorCode\":\"payload_too_large\",\"errorType\":\"invalid_request_error\",\"errorLink\":\"https://docs.meilisearch.com/error/payload_too_large\"}")', src/search/indexing/mod.rs:38:5
`

**Comment by Mubelotix** [comment]
That's a server error and the panic seems to be originated from your code (unwrap). It seems that the only thing I can do is adding this error to the Error enum (which is very incomplete for now).

**Comment by curquiza** [comment]
Hello @Geometrically and @Mubelotix, can we close this issue then? 🙂

**Comment by Mubelotix** [comment]
Yes, the new error enum will fix this soon.

**Comment by Geometrically** [comment]
I stil believe this is an issue, meilisearch's native API has no limits on payload sizes, this limit is imposed by the SDK. Could an option be made to increase the limit?

**Comment by curquiza** [comment]
Does it help? https://docs.meilisearch.com/guides/advanced_guides/configuration.html#payload-limit-size

**Comment by curquiza** [comment]
@Geometrically Does it help? https://docs.meilisearch.com/guides/advanced_guides/configuration.html#payload-limit-size

**Comment by Mubelotix** [comment]
No @Geometrically . As you saw in your error message, it is a meilisearch error coming directly from the server.

**Comment by Geometrically** [comment]
Oh, I see, seems to be something introduced with the actix switch. I'll close this, thanks for your help.

**Comment by Mubelotix** [comment]
Yeah but they are aware of this change since the message is a well formatted error message.

**Comment by curquiza** [comment]
@Geometrically! Yes it was introduced quite recently if I'm not wrong, that maybe you haven't seen it!

Hope you are ok and ready to use MeiliSearch and meilisearch-rust SDK now! 😁 Feel free to ask any question and to give us feedbacks!
