### ISSUE TITLE
Update to tokio 1.0

### ISSUE THREAD

**Issue by abour** [meilisearch/meilisearch-rust#79]
Reqwest is now using tokio 1.0 (https://github.com/seanmonstar/reqwest/pull/1076 was merged), so I think the update could be done now ?

EDIT: Actually I just figured out that even if it has been merged into master, not tag were added.

**Comment by curquiza** [comment]
Hello @abour!
Feel free to open a PR when the tag will be added then 😁

**Comment by Mubelotix** [comment]
It is not necessary since this crate will not use `reqwest` anymore in the next versions.

**Comment by abour** [comment]
Ok thank you good to know !
