### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-rust#9]
The README should have the same template as the other SDKs, but stay consistent with the Rust necessities of the language, of course.

The README should contain at least:

- A table of content
- An installation section
- A Getting Started section
- An Examples sections (with search, indexes manipulation, documents manipulation and updates)
- A Development Workflow and Contributing section that redirect to a CONTRIBUTING.md file (see this issue #8)
- A footer (see the README below)
- All other needed sections (WASM, How to generate the docs if present...)

Should be highly inspired by [this README](https://github.com/meilisearch/meilisearch-python)

**Comment by Mubelotix** [comment]
The readme is not up to date. The readme should be written in the documentation code in src/lib.rs and then generated by `cargo readme` (must be installed). But the generated file (README.md) has been updated manually and the source has not been changed so we have to update the source (lib.rs) to include the changes made manually in the README.md file.

There is also some out to date information in the doc like the version of the crate which is still 0.1. Please update pieces of information directly in src/lib.rs and then run `cargo readme` to avoid differences between these two files.

**Comment by curquiza** [comment]
Ok, this issue is only about the manual README, the front page, to be consistent with the other SDKs READMEs. I'm going to open another issue for the generated one since it needs installation and configuration compared to a "classical" README.

Yes, the version is not up-to-date on the current README, but no rush, we are still a WIP 😉 I will change that asap.

**Comment by curquiza** [comment]
This PR #31 solves this issue and gives an example about what we want as a template to solve this issue #27!
